### ISSUE TITLE
Error of extension

### ISSUE THREAD

**Issue by hktkzyx** [dongfg/vscode-beancount-formatter#6]
When I use this extension to format my beancount file, an error occurs that "Error call 'bean-format' command. Please check command in extension config and test in your terminal."
vscode
Version: 1.41.1 (user setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

beancount version: 2.2.3

**Comment by dongfg** [comment]
Are you using with a workspace(not a single file open)? 
The error occurs because the extension cannot invoke 'bean-format' command correctly.
Try test with following steps:
- Open your beancount folder
- Set the 'bin path' config of extension  to default `bean-format`
- Open a terminal in vscode and test `bean-format` command

**Comment by hktkzyx** [comment]
Yes, it is in the workspace. I have checked `bean-format` command in terminal and it works well. Is it because my python version is 3.8?

**Comment by dongfg** [comment]
It doesn't matter with python version, just a command call.
https://github.com/dongfg/vscode-beancount-formatter/blob/d18c7b6b915c5b11d09b7065e55f8b871f56ce34/src/extension.ts#L39

**Comment by dongfg** [comment]
I publish a new version with more error message in console. 
open `Help -> Toggle Developer Tools` to get more detail

**Comment by dongfg** [comment]
There is a bug when get workspace path, fix on `1.2.3`
